services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: hvac-dynamodb
    ports:
      - "3131:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - ./db-data:/home/dynamodblocal/data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: hvac-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
